OPSEXP-2849 Allow building and testing multiple versions of ACS
Alfresco/alfresco-dockerfiles-bakery pull request #110
Opened 2024-11-04 13:13 UTC by pmacius

### Description

Adding possibility to build multiple versions

### Related Issue

OPSEXP-2849

### Checklist

- [ ] My code follows the project's coding standards.
- [ ] I have updated the documentation accordingly.

2024-11-06 13:35 UTC, gionn commented on .github/workflows/build_and_test.yml
> +      acs_version: ${{ matrix.version }}
you probably need just tag and acs_version here, hardcode them in the reusable workflow (we don't really need to make them dynamic on caller)

2024-11-06 13:36 UTC, gionn commented on .github/workflows/reusuable_build_and_test.yml
check the typo in the filename

2024-11-07 11:40 UTC, gionn reviewed
everything else LGTM

2024-11-07 11:40 UTC, gionn commented on .github/workflows/reusable_build_and_test.yml
> +name: CI
```suggestion
name: Build and Test
run-name: Build v${{ inputs.acs_version }}
```

to make it better:

<img width="616" alt="Screenshot 2024-11-07 at 12 37 44" src="https://github.com/user-attachments/assets/676ecdaa-9886-4bba-9f60-37e7989d46b0">

2024-11-07 12:51 UTC, gionn approved these changes

2024-11-07 14:16 UTC, gionn commented on .github/workflows/cleanup_images.yml
> +          use-regex: true
```suggestion
```

was remembering wrong, looks like `*` is supported without the regexp switch
https://github.com/dataaxiom/ghcr-cleanup-action?tab=readme-ov-file#delete-tags

2024-11-07 15:23 UTC, gionn approved these changes

2024-11-07 16:28 UTC, alxgomz requested changes

2024-11-07 16:28 UTC, alxgomz commented on scripts/fetch-artifacts.sh
> +INDEX_KEY=${ACS_VERSION}
Good point. So in the end you can also remove `$INDEX_KEY` just use `$ACS_VERSION` as an index key.

2024-11-07 16:28 UTC, alxgomz commented on Makefile
> +TOMCAT_SHA512 := $(shell yq e '.${TOMCAT_FIELD}.sha512' $(TOMCAT_VERSIONS_FILE))
Can you add `yq` in the prereq section of the readme file?

2024-11-07 16:53 UTC, alxgomz approved these changes

2024-11-07 16:53 UTC, merged